const IMAGE_PATHS = "../assets/images";
export const ImageAssets = {
  cartWhite: require(`${IMAGE_PATHS}/icons/cart-white.png`),
  searchWhite: require(`${IMAGE_PATHS}/icons/search-white.png`),
  profileIcon: require(`${IMAGE_PATHS}/icons/profile-icon.png`),
  angleBackWhite: require(`${IMAGE_PATHS}/icons/angleBackWhite.png`),
  filter: require(`${IMAGE_PATHS}/icons/filter.png`),
  trash: require(`${IMAGE_PATHS}/icons/trash.png`),
  plus: require(`${IMAGE_PATHS}/icons/plus.png`),
  bag: require(`${IMAGE_PATHS}/icons/bag.png`),
  finger: require(`${IMAGE_PATHS}/icons/finger.png`),
  minus: require(`${IMAGE_PATHS}/icons/minus.png`),
  arrowLeft: require(`${IMAGE_PATHS}/icons/arrow-left.png`),
  black_back: require(`${IMAGE_PATHS}/icons/black_back.png`),
  fb: require(`${IMAGE_PATHS}/icons/fb.png`),
  contsact: require(`${IMAGE_PATHS}/icons/Contsact.png`),
  bell: require(`${IMAGE_PATHS}/icons/bell.png`),
  whatsapp: require(`${IMAGE_PATHS}/icons/whatsapp.png`),
  Settings: require(`${IMAGE_PATHS}/icons/Settings.png`),
  Referal: require(`${IMAGE_PATHS}/icons/Referal.png`),
  Cards: require(`${IMAGE_PATHS}/icons/Cards.png`),
  Transactions: require(`${IMAGE_PATHS}/icons/Transactions.png`),
  logo: require(`${IMAGE_PATHS}/logo.png`),
  logoPrimaryColor: require(`${IMAGE_PATHS}/logo-primary-color.png`),
  comingsoon: require(`${IMAGE_PATHS}/comingsoon.png`),
  logoBlack: require(`${IMAGE_PATHS}/logo-black.png`),
  image_picker: require(`${IMAGE_PATHS}/image-picker.png`),
  logoWhite: require(`${IMAGE_PATHS}/logo-white.png`),
  authBg: require(`${IMAGE_PATHS}/auth-bg.jpeg`),
  poweadBy: require(`${IMAGE_PATHS}/powead-by.png`),
  demo_user: require(`${IMAGE_PATHS}/demo-user.png`),
  arrowRight: require(`${IMAGE_PATHS}/icons/arrow-right.png`),
};
