import LocalizedStrings from "react-native-localization";
let localizedStrings = new LocalizedStrings({
  "en-US": {
    SignInScreen: "Sign In Screen",
    home: "Home",
    categories: "Categories",
    notifications: "Notifications",
    account: "Account",
    myAccount: "My Account",
    areYouSureYouWantToLogout: "Are you sure you want to logout?",
    ifYouLogoutYouWillNotBeAbleToReceiveAnyNotifications:
      "If you logout you will not be able to receive any notifications",
    cancel: "Cancel",
    ok: "Ok",
    myProfile: "My Profile",
    signInToYourAccount: "Sign in to your account",
    viewAndEditYourProfile: "View and edit your profile",
    setUpYourAccount: "Set up your account",
    signOut: "Sign Out",
    manageYourNotifications: "Manage your notifications",
    carts: "Carts",
    viewYourCart: "View your cart",
    inviteFriends: "Invite Friends",
    inviteYourFriendsToJoin: "Invite your friends to join",
    rateUs: "Rate Us",
    rateUsOnTheAppStore: "Rate us on the App Store",
    settings: "Settings",
    manageYourSettings: "Manage your settings",
    termsOfService: "Terms of Service",
    aboutUs: "About Us",
    phoneNumberIsRequired: "Phone number is required",
    tooShort: "Too short",
    passwordIsRequired: "Password is required",
    tooLong: "Too long",
    mobileNumber: "Mobile Number",
    enterYourMobileNumber: "Enter your mobile number",
    password: "Password",
    signIn: "Sign In",
    donTHaveAnAccount: "Don't have an account?",
    singUp: "Sign Up",
    useYourFigurePrintForExtraSecurityFromSettings:
      "Use your figure print for extra security from settings",
    nameIsRequired: "Name is required",
    emailIsRequired: "Email is required",
    name: "Name",
    email: "Email",
    invalidEmail: "Invalid email",
    enterYourName: "Enter your name",
    enterYourEmail: "Enter your email",
    iReadAndAgreeToThe: "I read and agree to the terms of service",
    and: "and",
    privacyPolicy: "Privacy Policy",
    alreadyHaveAnAccount: "Already have an account?",
    signInWithGoogle: "Sign in with Google",
  },
  bn: {
    SignInScreen: "সাইন ইন স্ক্রিন",
    home: "হোম",
    categories: "বিভাগ",
    notifications: "বিজ্ঞপ্তি",
    account: "অ্যাকাউন্ট",
    myAccount: "আমার অ্যাকাউন্ট",
    areYouSureYouWantToLogout: "আপনি কি নিশ্চিত যে আপনি লগ আউট করতে চান?",
    ifYouLogoutYouWillNotBeAbleToReceiveAnyNotifications:
      "আপনি লগ আউট করলে আপনি কোন বিজ্ঞপ্তি পাবেন না",
    cancel: "বাতিল",
    ok: "ঠিক আছে",
    myProfile: "আমার প্রোফাইল",
    signInToYourAccount: "আপনার অ্যাকাউন্টে সাইন ইন করুন",
    viewAndEditYourProfile: "আপনার প্রোফাইল দেখুন এবং সম্পাদনা করুন",
    setUpYourAccount: "আপনার অ্যাকাউন্ট সেট আপ করুন",
    signOut: "সাইন আউট",
    manageYourNotifications: "আপনার বিজ্ঞপ্তি পরিচালনা করুন",
    carts: "কার্ট",
    viewYourCart: "আপনার কার্ট দেখুন",
    inviteFriends: "বন্ধুদের আমন্ত্রণ করুন",
    inviteYourFriendsToJoin: "আপনার বন্ধুদের যোগদান করার জন্য আমন্ত্রণ করুন",
    rateUs: "আমাদের রেট করুন",
    rateUsOnTheAppStore: "অ্যাপ স্টোরে আমাদের রেট করুন",
    settings: "সেটিংস",
    manageYourSettings: "আপনার সেটিংস পরিচালনা করুন",
    termsOfService: "সেবা শর্তাবলী",
    aboutUs: "আমাদের সম্পর্কে",
    phoneNumberIsRequired: "ফোন নম্বর প্রয়োজন",
    tooShort: "খুব ছোট",
    passwordIsRequired: "পাসওয়ার্ড প্রয়োজন",
    tooLong: "খুব দীর্ঘ",
    mobileNumber: "মোবাইল নম্বর",
    enterYourMobileNumber: "আপনার মোবাইল নম্বর লিখুন",
    password: "পাসওয়ার্ড",
    signIn: "সাইন ইন করুন",
    donTHaveAnAccount: "কোন অ্যাকাউন্ট নেই?",
    singUp: "সাইন আপ করুন",
    useYourFigurePrintForExtraSecurityFromSettings:
      "সেটিংস থেকে অতিরিক্ত নিরাপত্তা জন্য আপনার চিত্র প্রিন্ট ব্যবহার করুন",
    nameIsRequired: "নাম প্রয়োজন",
    emailIsRequired: "ইমেল প্রয়োজন",
    name: "নাম",
    email: "ইমেল",
    invalidEmail: "অবৈধ ইমেল",
    enterYourEmail: "আপনার ইমেল লিখুন",
    enterYourName: "আপনার নাম লিখুন",
    iReadAndAgreeToThe: "আমি পড়েছি এবং সম্মত",
    and: "এবং",
    privacyPolicy: "গোপনীয়তা নীতি",
    alreadyHaveAnAccount: "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
    signInWithGoogle: "গুগল দিয়ে সাইন ইন করুন",
  },
});
let currentLocalizedLanguage = localizedStrings.getLanguage();
export { localizedStrings, currentLocalizedLanguage };
